---
# When changing options in this file, please also run:
#    python3 script/generate.py dev
# to update the dev addon config (beta/stable configs will be updated on next release by release script)
base: &base
  url: https://esphome.io/
  arch:
    - amd64
    - armv7
    - aarch64
  # Uses Home Assistant Supervisor API (auth)
  hassio_api: true
  auth_api: true
  # Host network mode for mDNS
  host_network: true
  # Ingress settings
  ingress: true
  ingress_port: 0
  panel_icon: 'mdi:chip'
  # Automatically add UART devices to add-on
  uart: true
  ports:
    '6052/tcp': null
  ports_description:
    '6052/tcp': "Web interface (not required for Home Assistant ingress)"
  map:
    - ssl:ro
    - config:rw
  schema:
    ssl: bool?
    certfile: str?
    keyfile: str?
    leave_front_door_open: bool?
    streamer_mode: bool?
    relative_url: str?
    status_use_ping: bool?
  backup_exclude:
    - "*/*/"

esphome-dev:
  <<: *base
  directory: esphome-dev
  name: ESPHome (dev)
  version: 'dev'  # DEV
  slug: esphome-dev
  description: "Development version of ESPHome add-on"
  url: https://next.esphome.io/
  stage: experimental
  schema:
    ssl: bool?
    certfile: str?
    keyfile: str?
    leave_front_door_open: bool?
    streamer_mode: bool?
    relative_url: str?
    status_use_ping: bool?
    esphome_fork: str?
  base_image: ghcr.io/esphome/esphome-hassio-{arch}:dev

esphome-beta:
  <<: *base
  directory: esphome-beta
  name: ESPHome (beta)
  version: '2021.11.1'  # BETA
  slug: esphome-beta
  description: "Beta version of ESPHome add-on"
  url: https://beta.esphome.io/
  image: ghcr.io/esphome/esphome-hassio-{arch}
  stage: experimental

esphome-stable:
  <<: *base
  directory: esphome
  name: ESPHome
  version: '2021.11.1'  # STABLE
  slug: esphome
  description: "ESPHome add-on for intelligently managing all your ESP8266/ESP32 devices"
  image: ghcr.io/esphome/esphome-hassio-{arch}

copy_files:
  icon.png:
  logo.png:
  README.md:
  DOCS.md:
  CHANGELOG.md:
