---
# When changing options in this file, please also run:
#    python3 script/generate.py dev
# to update the dev addon config (beta/stable configs will be updated on next release by release script)
base: &base
  url: https://esphome.io/
  arch:
    - amd64
    - aarch64
  # Uses Home Assistant Supervisor API (auth)
  hassio_api: true
  auth_api: true
  # Host network mode for mDNS
  host_network: true
  # Ingress settings
  ingress: true
  ingress_port: 0
  panel_icon: "mdi:chip"
  # Automatically add UART devices to add-on
  uart: true
  ports:
    "6052/tcp": null
  map:
    - ssl:ro
    - config:rw
  discovery:
    - esphome
  schema:
    status_use_ping: bool?
    streamer_mode: bool?
    home_assistant_dashboard_integration: bool?
    default_compile_process_limit: int(1,)?
    ssl: bool?
    certfile: str?
    keyfile: str?
    leave_front_door_open: bool?
  backup_exclude:
    - "*/*/"
  # Disable docker init for s6
  init: false
  # Make sure dashboard is available for core
  startup: services

esphome-dev:
  <<: *base
  directory: esphome-dev
  name: ESPHome Device Builder (dev)
  panel_title: ESPHome Builder (dev)
  version: "2025.10.0-dev20250924"  # DEV
  slug: esphome-dev
  description: "Development version of ESPHome Device Builder"
  url: https://next.esphome.io/
  image: ghcr.io/esphome/esphome-hassio
  stage: experimental
  advanced: true
  schema:
    status_use_ping: bool?
    streamer_mode: bool?
    home_assistant_dashboard_integration: bool?
    default_compile_process_limit: int(1,)?
    esphome_fork: str?
    ssl: bool?
    certfile: str?
    keyfile: str?
    leave_front_door_open: bool?
  options:
    home_assistant_dashboard_integration: false

esphome-beta:
  <<: *base
  directory: esphome-beta
  name: ESPHome Device Builder (beta)
  panel_title: ESPHome Builder (beta)
  version: "2025.9.1"  # BETA
  slug: esphome-beta
  description: "Beta version of ESPHome Device Builder"
  url: https://beta.esphome.io/
  image: ghcr.io/esphome/esphome-hassio
  stage: experimental
  advanced: true
  options:
    home_assistant_dashboard_integration: false

esphome-stable:
  <<: *base
  directory: esphome
  name: ESPHome Device Builder
  panel_title: ESPHome Builder
  version: "2025.9.1"  # STABLE
  slug: esphome
  description: "Build your own smart home devices using ESPHome, no programming experience required"
  image: ghcr.io/esphome/esphome-hassio

copy_files:
  - DOCS.md
  - icon.png
  - logo.png
  - README.md
  - translations/en.yaml
  - images/dht-example.png
  - images/screenshot.png
  - images/temperature-humidity.png
