---
url: https://next.esphome.io/
arch:
- amd64
- aarch64
hassio_api: true
auth_api: true
host_network: true
ingress: true
ingress_port: 0
panel_icon: mdi:chip
uart: true
ports:
  6052/tcp: null
map:
- ssl:ro
- config:rw
discovery:
- esphome
schema:
  status_use_ping: bool?
  streamer_mode: bool?
  home_assistant_dashboard_integration: bool?
  default_compile_process_limit: int(1,)?
  esphome_fork: str?
  ssl: bool?
  certfile: str?
  keyfile: str?
  leave_front_door_open: bool?
backup_exclude:
- '*/*/'
init: false
startup: services
name: ESPHome Device Builder (dev)
panel_title: ESPHome Builder (dev)
version: 2026.2.0-dev20260122
slug: esphome-dev
description: Development version of ESPHome Device Builder
image: ghcr.io/esphome/esphome-hassio
stage: experimental
advanced: true
options:
  home_assistant_dashboard_integration: false
