---
url: https://esphome.io/
arch:
- amd64
- armv7
- aarch64
hassio_api: true
auth_api: true
host_network: true
ingress: true
ingress_port: 0
panel_icon: mdi:chip
uart: true
ports:
  6052/tcp: null
map:
- ssl:ro
- config:rw
discovery:
- esphome
schema:
  status_use_ping: bool?
  streamer_mode: bool?
  home_assistant_dashboard_integration: bool?
  default_compile_process_limit: int(1,)?
  ssl: bool?
  certfile: str?
  keyfile: str?
  relative_url: str?
  leave_front_door_open: bool?
backup_exclude:
- '*/*/'
init: false
name: ESPHome
version: 2023.2.2
slug: esphome
description: ESPHome add-on for intelligently managing all your ESP8266/ESP32 devices
image: ghcr.io/esphome/esphome-hassio
