---
arch:
- amd64
- armv7
- aarch64
auth_api: true
backup_exclude:
- '*/*/'
description: ESPHome add-on for intelligently managing all your ESP8266/ESP32 devices
hassio_api: true
host_network: true
image: ghcr.io/esphome/esphome-hassio-{arch}
ingress: true
ingress_port: 0
init: false
map:
- ssl:ro
- config:rw
name: ESPHome
panel_icon: mdi:chip
ports:
  6052/tcp: null
ports_description:
  6052/tcp: Web interface (not required for Home Assistant ingress)
schema:
  certfile: str?
  default_compile_process_limit: int(1,)?
  keyfile: str?
  leave_front_door_open: bool?
  relative_url: str?
  ssl: bool?
  status_use_ping: bool?
  streamer_mode: bool?
slug: esphome
uart: true
url: https://esphome.io/
version: 2022.11.4
