name: Lint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Add-on configuration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channels:
          - folder: esphome
            channel: stable
          - folder: esphome-beta
            channel: beta
          - folder: esphome-dev
            channel: dev
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v2
      - name: ğŸ›  Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: ğŸ›  Install dependencies
        run: pip install -r script/requirements.txt
      - name: ğŸ›  Generate files from template
        run: python script/generate.py ${{ matrix.channels.channel }}
      - name: ğŸš€ Run Home Assistant Add-on Lint on ${{ matrix.channels.channel }}
        uses: frenck/action-addon-linter@v2
        with:
          path: "./${{ matrix.channels.folder }}"
