name: Lint
on: [push, pull_request]
jobs:
  build:
    name: Add-on configuration
    runs-on: ubuntu-latest
    strategy:
       matrix:
         channel: [esphome, esphome-beta, esphome-dev]
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v2
      - name: ğŸ›  Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: ğŸ›  Install dependencies
        run: pip install -r script/requirements.txt
      - name: ğŸ›  Generate files from template
        run: python script/generate.py dev beta stable
      - name: ğŸš€ Run Home Assistant Add-on Lint on ${{ matrix.channel }}
        uses: frenck/action-addon-linter@v2
        with:
          path: "./${{ matrix.channel }}"
