name: Lint
on: [push, pull_request]
jobs:
  build:
    name: Add-on configuration
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v2
      - name: ğŸš€ Run Home Assistant Add-on Lint on ESPHome
        uses: frenck/action-addon-linter@v2
        with:
          path: "./esphome"
      - name: ğŸš€ Run Home Assistant Add-on Lint on ESPHome-Beta
        uses: frenck/action-addon-linter@v2
        with:
          path: "./esphome-beta"
      - name: ğŸš€ Run Home Assistant Add-on Lint on ESPHome-Dev
        uses: frenck/action-addon-linter@v2
        with:
          path: "./esphome-dev"
